language: generic 
sudo: required
services:
  # Tells Travis we need docker
  - docker

# Series of commands / setup executed before our tests are ran
before_install:
  # Note that we are tagging the image below `-t <DOCKER_USER/GIT_REPO_NAME>`
  # We could use any tag name though, as the tag will only be used inside this travis process.
  - docker build -t gregoryforel/docker-react -f Dockerfile.dev .

script:
  # We override environment variables with -e CI=TRUE
  # CI=TRUE forces Jest to run in CI-mode, and tests will only run once instead of launching the watcher.
  # Otherwise, Travis would hang forever hoping for Node to exit the tests before continuing the process.
  - docker run -e CI=true gregoryforel/docker-react npm run test

deploy:
  # Travis is pre-configured with some providers. ElasticBeanstalk is one of them
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  # When Travis deploys, it's gonna take all the file and zip them into one.
  # We will put that on an AWS S3 instance. Beanstalk already prepared it for us.
  bucket_name: "elasticbeanstalk-eu-west-1-907738920570"
  bucket_path: "docker" # Should be equal to your app name
  on:
    # We only deploy when master is updated.
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

  # Docker-env.eba-a5rbxpum.eu-west-1.elasticbeanstalk.com